[Fixed #165] Fixed NoClassDefFoundError caused by method count overflow
* Import required libraries only (for now, only analytics) to meet the limit
* Handle MultiDex Support to prevent possible crash in the future